# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class QueryTerms(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, disease: str=None, symptom: str=None, protein: str=None, anatomical_entity: str=None, chemical_substance: str=None, metabolite: str=None, pathway: str=None, gene: str=None, cell: str=None):  # noqa: E501
        """QueryTerms - a model defined in Swagger

        :param disease: The disease of this QueryTerms.  # noqa: E501
        :type disease: str
        :param symptom: The symptom of this QueryTerms.  # noqa: E501
        :type symptom: str
        :param protein: The protein of this QueryTerms.  # noqa: E501
        :type protein: str
        :param anatomical_entity: The anatomical_entity of this QueryTerms.  # noqa: E501
        :type anatomical_entity: str
        :param chemical_substance: The chemical_substance of this QueryTerms.  # noqa: E501
        :type chemical_substance: str
        :param metabolite: The metabolite of this QueryTerms.  # noqa: E501
        :type metabolite: str
        :param pathway: The pathway of this QueryTerms.  # noqa: E501
        :type pathway: str
        :param gene: The gene of this QueryTerms.  # noqa: E501
        :type gene: str
        :param cell: The cell of this QueryTerms.  # noqa: E501
        :type cell: str
        """
        self.swagger_types = {
            'disease': str,
            'symptom': str,
            'protein': str,
            'anatomical_entity': str,
            'chemical_substance': str,
            'metabolite': str,
            'pathway': str,
            'gene': str,
            'cell': str
        }

        self.attribute_map = {
            'disease': 'disease',
            'symptom': 'symptom',
            'protein': 'protein',
            'anatomical_entity': 'anatomical_entity',
            'chemical_substance': 'chemical_substance',
            'metabolite': 'metabolite',
            'pathway': 'pathway',
            'gene': 'gene',
            'cell': 'cell'
        }

        self._disease = disease
        self._symptom = symptom
        self._protein = protein
        self._anatomical_entity = anatomical_entity
        self._chemical_substance = chemical_substance
        self._metabolite = metabolite
        self._pathway = pathway
        self._gene = gene
        self._cell = cell

    @classmethod
    def from_dict(cls, dikt) -> 'QueryTerms':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Query_terms of this QueryTerms.  # noqa: E501
        :rtype: QueryTerms
        """
        return util.deserialize_model(dikt, cls)

    @property
    def disease(self) -> str:
        """Gets the disease of this QueryTerms.


        :return: The disease of this QueryTerms.
        :rtype: str
        """
        return self._disease

    @disease.setter
    def disease(self, disease: str):
        """Sets the disease of this QueryTerms.


        :param disease: The disease of this QueryTerms.
        :type disease: str
        """

        self._disease = disease

    @property
    def symptom(self) -> str:
        """Gets the symptom of this QueryTerms.


        :return: The symptom of this QueryTerms.
        :rtype: str
        """
        return self._symptom

    @symptom.setter
    def symptom(self, symptom: str):
        """Sets the symptom of this QueryTerms.


        :param symptom: The symptom of this QueryTerms.
        :type symptom: str
        """

        self._symptom = symptom

    @property
    def protein(self) -> str:
        """Gets the protein of this QueryTerms.


        :return: The protein of this QueryTerms.
        :rtype: str
        """
        return self._protein

    @protein.setter
    def protein(self, protein: str):
        """Sets the protein of this QueryTerms.


        :param protein: The protein of this QueryTerms.
        :type protein: str
        """

        self._protein = protein

    @property
    def anatomical_entity(self) -> str:
        """Gets the anatomical_entity of this QueryTerms.


        :return: The anatomical_entity of this QueryTerms.
        :rtype: str
        """
        return self._anatomical_entity

    @anatomical_entity.setter
    def anatomical_entity(self, anatomical_entity: str):
        """Sets the anatomical_entity of this QueryTerms.


        :param anatomical_entity: The anatomical_entity of this QueryTerms.
        :type anatomical_entity: str
        """

        self._anatomical_entity = anatomical_entity

    @property
    def chemical_substance(self) -> str:
        """Gets the chemical_substance of this QueryTerms.


        :return: The chemical_substance of this QueryTerms.
        :rtype: str
        """
        return self._chemical_substance

    @chemical_substance.setter
    def chemical_substance(self, chemical_substance: str):
        """Sets the chemical_substance of this QueryTerms.


        :param chemical_substance: The chemical_substance of this QueryTerms.
        :type chemical_substance: str
        """

        self._chemical_substance = chemical_substance

    @property
    def metabolite(self) -> str:
        """Gets the metabolite of this QueryTerms.


        :return: The metabolite of this QueryTerms.
        :rtype: str
        """
        return self._metabolite

    @metabolite.setter
    def metabolite(self, metabolite: str):
        """Sets the metabolite of this QueryTerms.


        :param metabolite: The metabolite of this QueryTerms.
        :type metabolite: str
        """

        self._metabolite = metabolite

    @property
    def pathway(self) -> str:
        """Gets the pathway of this QueryTerms.


        :return: The pathway of this QueryTerms.
        :rtype: str
        """
        return self._pathway

    @pathway.setter
    def pathway(self, pathway: str):
        """Sets the pathway of this QueryTerms.


        :param pathway: The pathway of this QueryTerms.
        :type pathway: str
        """

        self._pathway = pathway

    @property
    def gene(self) -> str:
        """Gets the gene of this QueryTerms.


        :return: The gene of this QueryTerms.
        :rtype: str
        """
        return self._gene

    @gene.setter
    def gene(self, gene: str):
        """Sets the gene of this QueryTerms.


        :param gene: The gene of this QueryTerms.
        :type gene: str
        """

        self._gene = gene

    @property
    def cell(self) -> str:
        """Gets the cell of this QueryTerms.


        :return: The cell of this QueryTerms.
        :rtype: str
        """
        return self._cell

    @cell.setter
    def cell(self, cell: str):
        """Sets the cell of this QueryTerms.


        :param cell: The cell of this QueryTerms.
        :type cell: str
        """

        self._cell = cell
