SELECT DISTINCT PREDICATE FROM PREDICATION WHERE SUBJECT_SEMTYPE = 'cell' AND OBJECT_SEMTYPE = 'dsyn' LIMIT 10;
#SELECT * FROM PREDICATION WHERE SUBJECT_SEMTYPE = 'moft' AND OBJECT_SEMTYPE = 'dsyn' LIMIT 10;
SELECT * FROM PREDICATION WHERE SUBJECT_SEMTYPE = 'dsyn' AND OBJECT_SEMTYPE = 'moft' LIMIT 10;

SELECT * FROM PREDICATION WHERE SUBJECT_SEMTYPE = 'celf' AND OBJECT_SEMTYPE = 'dsyn' LIMIT 10;
SELECT * FROM PREDICATION WHERE SUBJECT_SEMTYPE = 'dsyn' AND OBJECT_SEMTYPE = 'celf' LIMIT 10;

SELECT * FROM PREDICATION WHERE SUBJECT_SEMTYPE = 'tisu' AND OBJECT_SEMTYPE = 'dsyn' LIMIT 10;
#SELECT * FROM PREDICATION WHERE SUBJECT_SEMTYPE = 'dsyn' AND OBJECT_SEMTYPE = 'tisu' LIMIT 10;

SELECT DISTINCT PREDICATE FROM PREDICATION WHERE (SUBJECT_SEMTYPE = 'celf' OR SUBJECT_SEMTYPE = 'moft') AND OBJECT_SEMTYPE = 'cell' LIMIT 10;
SELECT DISTINCT PREDICATE FROM PREDICATION WHERE SUBJECT_SEMTYPE = 'cell' AND (OBJECT_SEMTYPE = 'celf' OR OBJECT_SEMTYPE = 'moft') LIMIT 10;